### PR TITLE
make rpm package build easier

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by photron** [comment]
Why do you specifically override the "CFLAGS += -O2" line with RPM_OPT_FLAGS, but do nothing in WITH_DEBUG=yes is set? I'd expect something like this:

```diff
diff --git a/src/brickd/Makefile b/src/brickd/Makefile
index 206512d..44f571c 100644
--- a/src/brickd/Makefile
+++ b/src/brickd/Makefile
@@ -533,6 +533,10 @@ ifeq ($(WITH_UNKNOWN_LIBUSB_API_VERSION),yes)
 	CFLAGS += -DBRICKD_UNKNOWN_LIBUSB_API_VERSION
 endif
 
+ifdef RPM_OPT_FLAGS
+	CFLAGS += $(RPM_OPT_FLAGS)
+endif
+
 ifneq ($(MAKECMDGOALS),clean)
 $(info libraries/tools:)
 $(info - libusb:                     $(LIBUSB_STATUS))
```

About the syslibdir change to change the systemd service location: Your assertion "systemd unit files are always in $prefix/lib/systemd" is not correct. In contrast to the systemd documentation Debian puts the service files at /lib/systemd/system. We mostly use Debian here, so this is modeled after Debian.

The correct way of doing this would be to use syslibdir on Debian and libdir on non-Debian as systemd service location.

I could add a systemddir variable that defaults to $(syslibdir)/systemd, so the existing behavior does not change, but you could override it to /usr/lib/systemd.

Something like this:

```diff
diff --git a/src/brickd/Makefile b/src/brickd/Makefile
index 206512d..4baf435 100644
--- a/src/brickd/Makefile
+++ b/src/brickd/Makefile
@@ -86,6 +86,10 @@ ifndef libdir
 	libdir := $(prefix)/lib
 endif
 
+ifndef systemddir
+	systemddir := $(syslibdir)/systemd
+endif
+
 ifneq ($(findstring $(MAKEFLAGS),s),s)
 ifndef V
 	E := @
@@ -614,8 +622,8 @@ ifeq ($(WITH_PM_UTILS),yes)
 endif
 
 ifeq ($(WITH_SYSTEMD),yes)
-	@echo MD $(syslibdir)/systemd/system
-	$(E)$(INSTALL) -d -m 755 $(DESTDIR)$(syslibdir)/systemd/system
+	@echo MD $(systemddir)/system
+	$(E)$(INSTALL) -d -m 755 $(DESTDIR)$(systemddir)/system
 endif
 
 	@echo CP brickd
@@ -633,7 +641,7 @@ ifeq ($(WITH_SYSTEMD),no)
 	$(E)$(INSTALL) -m 755 ../build_data/linux/installer/usr/share/brickd/brickd-sysv-init $(DESTDIR)$(sysconfdir)/init.d/brickd
 else
 	@echo CP brickd.service [systemd service]
-	$(E)$(INSTALL) -m 644 ../build_data/linux/installer/lib/systemd/system/brickd.service $(DESTDIR)$(syslibdir)/systemd/system
+	$(E)$(INSTALL) -m 644 ../build_data/linux/installer/lib/systemd/system/brickd.service $(DESTDIR)$(systemddir)/system
 endif
 
 	@echo CP brickd [logrotate.d script]
@@ -656,7 +664,7 @@ endif
 
 ifeq ($(WITH_SYSTEMD),yes)
 	@echo CP brickd-resume.service [systemd service]
-	$(E)$(INSTALL) -m 644 ../build_data/linux/installer/lib/systemd/system/brickd-resume.service $(DESTDIR)$(syslibdir)/systemd/system
+	$(E)$(INSTALL) -m 644 ../build_data/linux/installer/lib/systemd/system/brickd-resume.service $(DESTDIR)$(systemddir)/system
 endif
 
 %.o: %.c Makefile
```

**Comment by lnussel** [comment]
updated patches. Proposing another appoach for the CFLAGS. There's normally no need to work with +=. One can just set the default value. If specified on the command line it would be overridden anways.

Wrt to systemd I've rewritten the code to query pkg-config for the correct unit dir.

**Comment by photron** [comment]
The removal of the += usage breaks "CFLAGS=foobar make" usage. I've restored the += usage now.

**Comment by lnussel** [comment]
use "make CFLAGS=foobar"

**Comment by photron** [comment]
"CFLAGS=foobar make" and "make CFLAGS=foobar" don't result in the same thing. The first one presets CFLAGS with foobar and any += usage in the Makefile then adds to it. The second overrides what ever the Makefile assigns to CFLAGS with foobar.

**Pull request merged**
